version: "3.1"

services:
  sqlserver:
    build:
      context: .
    user: "0:0"
    container_name: ${SQLSV_NAME}
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      USERNAME: ${SLSV_USER}
      SA_PASSWORD: ${SQLSV_PWD}
      SSQL_PID: Express
    volumes:
      - ./docker/sqlserver-data:/var/opt/mssql
      - ./scripts:/scripts