#!/bin/bash

display_help() {
   # Display Help
   echo "======================================"
   echo "   Docker start a AWS glue spark shell"
   echo "======================================"
   echo "Syntax: docker-aws-glue [command]"
   echo
   echo "---commands---"
   echo "help                     Print CLI help"
   echo "pull                     Pull the glue libs image from dockerhub "
   echo "run                      Run the docker image and start the server at localhost:8888"
   echo "start                    Start the glue server. It requires the command run to be used before."
   echo "validate-prereqs       Validate pre-reqs installed (docker, docker-compose, aws cli)"  
}

validate_prereqs() {
   docker -v >/dev/null 2>&1
   if [ $? -ne 0 ]; then
      echo -e "'docker' is not installed or not runnable without sudo. \xE2\x9D\x8C"
   else
      echo -e "Docker is Installed. \xE2\x9C\x94"
   fi

   docker-compose -v >/dev/null 2>&1
   if [ $? -ne 0 ]; then
      echo -e "'docker-compose' is not installed. \xE2\x9D\x8C"
   else
      echo -e "Docker compose is Installed. \xE2\x9C\x94"
   fi

   aws --version >/dev/null 2>&1
   if [ $? -ne 0 ]; then
      echo -e "'Aws Cli' is not installed. \xE2\x9D\x8C"
   else
      echo -e "Aws Cli is Installed. \xE2\x9C\x94"
   fi
}

export_path() {
   export GLUE_PATH=$(pwd)
}

case "$1" in
validate-prereqs)
   validate_prereqs
   ;;
pull)
   docker pull amazon/aws-glue-libs:glue_libs_1.0.0_image_01
   ;;
run)
   export_path
   docker run -itd -p 8888:8888 -p 4040:4040 -v ~/.aws:/root/.aws:ro -v $GLUE_PATH/docker-glue/notebooks:/home/jupyter/jupyter_default_dir -v $GLUE_PATH/docker-glue/data:/home/docs --name glue_jupyter amazon/aws-glue-libs:glue_libs_1.0.0_image_01 /home/jupyter/jupyter_start.sh
   ;;
start)
   docker start glue_jupyter
   ;;
help)
   display_help
   ;;
*)
   echo "No command specified, displaying help"
   display_help
   ;;
esac
